name: Node.js CD

on:
  workflow_dispatch:
  push:
    branches: ['v2']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/ayumi
            rm -rf db.json
            rm -rf .env
            cp .env.example .env
            git pull origin v2
            npm install
            pm2 restart ayumi